#!/usr/bin/env python

import yaml
import jinja2
from slugify import slugify 

jinja_env = jinja2.Environment(
  autoescape = True,
  loader = jinja2.FileSystemLoader( searchpath = "./" )

  # Separadores LaTex
  # block_start_string = '\BLOCK{',
  # block_end_string = '}',
  # variable_start_string = '\VAR{',
  # variable_end_string = '}',
  # comment_start_string = '\#{',
  # comment_end_string = '}',
  # line_statement_prefix = '%%',
  # line_comment_prefix = '%#',
  # trim_blocks = True,
  # autoescape = False,

)

def slug(value):
    #return slugify(unidecode(value))
    return slugify( value )
jinja_env.filters['slug'] = slug

template = jinja_env.get_template( 'base.html' )

contenido = yaml.load(
  open( 'contenido.yml', 'r' ),
  Loader = yaml.FullLoader
)

with open( 'output.html', "w" ) as tex:
  tex.write( template.render( contenido = contenido ) )





