#!/usr/bin/env python

import yaml
import jinja2
from slugify import slugify 
from html5print import HTMLBeautifier
import datetime
import markdown

jinja_env = jinja2.Environment(
  autoescape = True,
  loader = jinja2.FileSystemLoader( searchpath = "./templates" )
)

def slug(value):
    return slugify( value )
jinja_env.filters['slug'] = slug

def md(value):
    return markdown.markdown(value)
jinja_env.filters['md'] = md

# def parrafos(value):
#     """ Remover párrafos vacíos"""
#     parrafos = value.split('\n')
#     o = ''
#     for parrafo in parrafos:
#       if parrafo:
#         o += '<p>' + parrafo + '</p>'
#     return o
# jinja_env.filters['parrafos'] = parrafos

template = jinja_env.get_template( 'base.html' )
template.globals['now'] = datetime.datetime.utcnow

contenido = yaml.load(
  open( 'contenido.yml', 'r' ),
  Loader = yaml.FullLoader
)

feo =  template.render( contenido = contenido ) 
lindo = HTMLBeautifier.beautify( feo, 2)
with open( 'build/index.html', "w" ) as tex:
  tex.write( lindo )


